### ISSUE TITLE
Falsche Fehlermeldung auf Android bei fehlendem Pflichtfeld

### ISSUE THREAD

**Issue by ghost** [mdatiqs/loop_op_tickets#1]
Anscheinend gibt es bei den "mobile" checks auf Android einen Fehler. Ein Kunde beschwerte sich, dass er den Check nicht abschließen kann und diesen Fehler bekommt:

 ![MicrosoftTeams-image](https://user-images.githubusercontent.com/69344390/122876267-9915c400-d335-11eb-91ff-cac27df083bd.png)

Er bekommt "Fehler" weil er die "mandatory" Felder nicht aufgefüllt hat, aber der Android Browser gibt leider nicht die Richtige Fehlermeldung aus. Irgendein "browser spezifischer case" wird da wohl nicht richtig behandelt.

**Comment by ghost** [comment]
SID: 97, CheckID: 1845

**Comment by MarcNerdforce** [comment]
closed by mdatiqs/loop_shopper#11
