### ISSUE TITLE
Timeout für Auth renew

### ISSUE THREAD

**Issue by MarcNerdforce** [mdatiqs/loop_op_tickets#10]
Fabian hatte mal im Zusammenhang vom debugging den Tokenrenewal timout hochgeschraupt.
Mir kommt es so vor als hätte er es nie runter gesetzt.
Kann man mal nachschauen wie lang der timeout jetzt ist und ob man Ihn erhöhen müsste?

**Comment by FabianGrueterich** [comment]
Ich habe das entsprechende Token Accesstokelifetime wieder auf 300 Sekunden runtergestellt gehabt, am 31. Mai. Das sollte also eigentlich keine Probleme machen.
