### ISSUE TITLE
Offlinespeicher übertragen - Button beim initialen Laden

### ISSUE THREAD

**Issue by ghost** [mdatiqs/loop_op_tickets#5]
mir ist aufgefallen, dass, wenn man sich initial als Shopper einloggt, beim ersten Aufruf eines Checks der "Offlinespeicher übertragen" immer angezeigt wird:
![image](https://user-images.githubusercontent.com/69344390/123584000-e89a3b00-d7e0-11eb-801b-8c14ddbd769f.png)
Sobald man den gedrückt hat, kann man ganz normal die Dateneingabe vornehmen und sieht die Schaltfläche auch nicht mehr, sobald man weitere Checks aufruft. Das ist verwirrend. Können wir die bitte nur einblenden, wenn die Schaltfläche auch "gebraucht" wird?

**Comment by MarcNerdforce** [comment]
Ich habe das umgebaut ,so dass die Cache nur bei ungespeichert aufgerufen wird
mdatiqs/loop_shopper@ff61f4a25b6d43fa194c1e6d074d076b5874abfa

![2021-06-28 09_16_22-Window](https://user-images.githubusercontent.com/76945940/123595757-9281c380-d7f1-11eb-9e2b-13a825d69b17.png)

**Comment by MarcNerdforce** [comment]
closed by mdatiqs/loop_shopper@ff61f4a25b6d43fa194c1e6d074d076b5874abfa
