### ISSUE TITLE
Role Type not found

### ISSUE THREAD

**Issue by MarcNerdforce** [mdatiqs/loop_op_tickets#9]
Auf :  https://projects.dsinux.hh-it.local/#/usermanagement

Problem: Role type missing error
![2021-07-03 16_07_38-Window](https://user-images.githubusercontent.com/76945940/124357062-cb6acf80-dc19-11eb-8997-482fd23365af.png)

Es sieht so aus als würde https://projects.dsinux.hh-it.local/api/Data/RoleTypes keine Guids übergeben die wir in den Usern haben
Beispiel https://projects.dsinux.hh-it.local/api/SecurityUsers/381ED5DD-66C7-4176-9316-2904142B165D #6 
```js
{
Active: true
CompanyName: "TestCopyFirma"
Country: "DE"
DefaultWelcomePage: "http://test.com"
FirstName: "Test123456"
Gender: "M"
LastName: "CopyUser"
Locked: 0
LoginName: "<yx<yx<yx"
RoleGuid: "FB108C83-FF35-43EB-B529-6D304EA0F27C"
RoleTypeGuid: "F2A0A5AD-AA34-419C-93A4-2BE3651B894F"
UserId: "381ED5DD-66C7-4176-9316-2904142B165D"
}
```

https://projects.dsinux.hh-it.local/api/Data/RoleTypes

```js
0: {RoleTypeGuid: "DC6FE6A8-4F49-49F0-870D-FFE9FD8B30DF", RoleTypeName: "Porsche_MSM"}
RoleTypeDisplayName: "Administrator"
RoleTypeGuid: "DC6FE6A8-4F49-49F0-870D-FFE9FD8B30DF"
RoleTypeName: "Porsche_MSM"
Roles: [{RoleGuid: "1ACF5645-F713-4876-AC15-6D3A921DB88C", RoleName: "Porsche_MSM_Administrator"}]
UserTypeId: 1
UserTypeName: "MSM"
1: {RoleTypeGuid: "4E3059F6-0DFC-41F6-96C7-A0F3B9879337", RoleTypeName: "Porsche_Agency"}
2: {RoleTypeGuid: "157F3526-D9FC-4F63-9180-0E165C685E3E", RoleTypeName: "Porsche_Client"}
3: {RoleTypeGuid: "F6BD85FE-6E47-4A01-BB6B-1E7D6883CBAB", RoleTypeName: "Porsche_Porsche"}
```

**Comment by speters-nerdforce** [comment]
Weil die Umgebungsvariable auf Porsche war, ist der Fehler aufgetreten, dsinux ist jetzt aber wieder auf MSM zurück gesetzt
